
# Setup
title:               Aquent Gymnasium
#url:                 http://gymnasium.github.io
baseurl:
#permalink: :year/:month/:day/:title/
#paginate:            5

# Custom vars
# Conversion
markdown:    kramdown
highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml


#gems: [jekyll-paginate]
repository: gymnasium/gymnasium.github.io
github:
  url: http://localhost:4000
